module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      require.resolve('babel-plugin-module-resolver'),
      {
        cwd: 'babelrc',
        extensions: [
          '.ios.ts',
          '.android.ts',
          '.ts',
          '.ios.tsx',
          '.android.tsx',
          '.tsx',
          '.jsx',
          '.js',
          '.json',
        ],
        alias: {
          '@base': ['./src/base'],
          '@components': ['./src/components'],
          '@controller': ['./src/controller'],
          '@constants': ['./src/constants'],
          '@database': ['./src/database'],
          '@items': ['./src/items'],
          '@network': ['./src/network'],
          '@res': ['./src/res'],
          '@values': ['./src/res/values'],
          '@styles': ['./src/res/styles'],
          '@router': ['./src/router'],
          '@screens': ['./src/screens'],
          '@store': ['./src/store'],
          '@reducers': ['./src/store/reducers'],
          '@sagas': ['./src/store/sagas'],
          '@utils': ['./src/utils'],
          '@types': ['./src/utils/types'],
          '@manager': ['./src/manager'],
        },
      },
    ],
  ],
};
